# File: veracode-sast-platform-job.yml

parameters:
- name: solution
  default: ''
  type: string

jobs:       
 - job: SAST_Security_Testing
   displayName: Static Analysis Security Testing

   steps:

   # step to validate required parameters
   - bash: |
        if [ -z "$SOLUTION" ]; then
          echo "##vso[task.logissue type=error;]Missing template parameter \"ArtifactName\""
          echo "##vso[task.complete result=Failed;]"
        fi

   - task: DownloadPipelineArtifact@2
     inputs:
        artifact: ${{ parameters.solution }}

   - bash: echo ${{ parameters.solution }}
   - bash: ls -la

   #- task: Veracode@3
   #  inputs:
   #     ConnectionDetailsSelection: 'Endpoint'
   #     AnalysisService: 'Veracode SaaS Connection'
        # apiId: '$(VERACODE_ID)'
        # apiKey: '$(VERACODE_KEY)'
   #     veracodeAppProfile: '$(system.teamProject)'
   #     version: '$(build.buildNumber)'
   #     filepath: '$(Pipeline.Workspace)'  #$(build.artifactstagingdirectory)
   #     sandboxName: 'Development Sandbox'
   #     failBuildIfUploadAndScanBuildStepFails: true
   #     importResults: true
       # failBuildOnPolicyFail: true
       # maximumWaitTime: '360'
