# File: veracode-sast-platform-job.yml

parameters:
- name: artifact
  default: ''
  type: string

jobs:       
 - job: Veracode_Platform_SAST
   displayName: Static Analysis Security Testing
   dependsOn: Build

   steps:
   # step to validate required parameters
   - bash: |
        if [ -z "$ARTIFACT" ]; then
          echo "##vso[task.logissue type=error;]Missing template parameter \"artifact\""
          echo "##vso[task.complete result=Failed;]"
        fi

   - task: DownloadPipelineArtifact@2
     inputs:
        artifact: ${{ parameters.artifact }}

   - bash: echo ${{ parameters.artifact }}
   - bash: ls -la

   - task: Veracode@3
     inputs:
        ConnectionDetailsSelection: 'Endpoint'
        AnalysisService: 'Veracode SaaS Connection'
        # apiId: '$(VERACODE_ID)'
        # apiKey: '$(VERACODE_KEY)'
        veracodeAppProfile: '$(system.teamProject)'
        version: '$(build.buildNumber)'
        filepath: '$(Pipeline.Workspace)'
        sandboxName: 'Development Sandbox'
        failBuildIfUploadAndScanBuildStepFails: true
        importResults: true
       # failBuildOnPolicyFail: true
       # maximumWaitTime: '360'
